#!/usr/bin/env bash

VERSION="development"
URL="http://snapshot.tumbleweed.boombatower.com:13372"

tumbleweed_status()
{
  echo "latest : $(tumbleweed_latest)"
  echo "current: $(tumbleweed_version)"
}

tumbleweed_latest()
{
  curl --silent "$URL/latest"
}

tumbleweed_version()
{
  cat /etc/os-release | grep -oP "VERSION_ID=\"\K(\d+)"
}

tumbleweed_list()
{
  curl --silent "$URL/list"
}

tumbleweed_switch()
{
}

tumbleweed_usage()
{
  cat <<_EOF_
Usage: $0 [options] command [arguments]

Options:
    --version         Print version string and exit
-h, --help            Display this message and exit

Commands:
status
latest
version
list
switch                wut
_EOF_
}

tumbleweed_handle()
{
  case "$1" in
    --version) echo "$VERSION" ; exit 0 ; ;;
    -h|--help) command="usage" ; ;;
    status|latest|version|list)
      command="$1" ; ;;
    switch)
      command="$1" ; args_expected=1 ;
      ;;
    -*) echo "unknown option $1" ; exit 1 ; ;;
    *)
      if [ $args_expected -eq 0 ] ; then
        return 1
      fi
      args+=("$1")
      ((args_expected--))
      ;;
  esac
  return 0
}

command="usage"
args_expected=0
args=()
while tumbleweed_handle $1 ; do
  shift
done

tumbleweed_$command ${args[@]}
